### PR TITLE
Enable tests again

### PR DESCRIPTION
**Pull request by peterrum**
Now that https://github.com/dealii/dealii/pull/11427 is merged, the docker image should be ready in the next hours so that we can enable the tests in the GitHub action again!

### CODE REVIEW

**Comment by peterrum** [comment]
```
The following tests FAILED:
	  1 - benchmark_basic_test/test.mpirun=1.debug (Failed)
	  2 - benchmark_basic_test/test.mpirun=4.debug (Failed)
	 10 - benchmark_s_step_test/test.mpirun=4.debug (Failed)
```
@kronbichler Could you have a look why the *basic* tests fail. I get `The violated condition was: std::abs(alpha) != 0.` Furthermore, I would suggest not to print the iteration numbers in the test: I have run `benchmark_s_step_test/test.mpirun=4.debug` and the output should be fine for our hardware (but the iteration number is one off).

**Comment by kronbichler** [comment]
Yes I agree, we should be tolerant iteration counts. On the other hand, we might want to use some criterion to inspect that iteration counts are say 10 and not 100. I am not sure how to achieve that.

**Comment by kronbichler** [comment]
The error should be fixed by #29.

**Comment by peterrum** [comment]
@kronbichler I don't have a solution for the iteration-number issue yet. But let's see if `benchmark_precond_merged` passes here.

**Comment by kronbichler** [comment]
I think now only the iteration counts are off, so if we remove those we should be good to go.

**Comment by peterrum** [comment]
I have updated deal.II and the `benchmark_precond_merged` tests still fail locally on the gold nodes (both for release and debug mode)...

**Comment by kronbichler** [comment]
Let us merge this one and I have a look at the gold nodes later. It might be some invalid access with AVX-512 that I don't see locally with AVX2 and that we don't trigger on the tester.

**Comment by kronbichler** [comment]
I tried to run it on gold but for me the output is fine (this is release and 1 MPI rank):
```
dim degree s  n_cells n_dofs n_it   error    
  3      1  1       2     36    0 8.1728e-01 
  3      1  2       4     54    0 8.1728e-01 
  3      1  3       8     81    2 5.3545e-01 
  3      1  4      16    135    2 5.3552e-01 
  3      1  5      32    225    8 5.3575e-01 
  3      1  6      64    375   10 5.3308e-01 
  3      1  7     128    675   12 5.3337e-01 
  3      1  8     256   1215   16 5.3360e-01 
  3      1  9     512   2187   20 1.6381e-01 
  3      1 10    1024   4131   23 1.6381e-01 
  3      1 11    2048   7803   30 1.6382e-01 
  3      2  1       2    135    2 6.0214e-01 
  3      2  2       4    225    9 5.6873e-01 
  3      2  3       8    375   11 5.2545e-01 
  3      2  4      16    675   13 5.2568e-01 
  3      2  5      32   1215   19 5.2594e-01 
  3      2  6      64   2187   26 1.1560e-01 
  3      2  7     128   4131   29 1.1554e-01 
  3      2  8     256   7803   38 1.1506e-01 
  3      2  9     512  14739   55 2.1551e-02 
  3      3  1       2    336    9 5.5036e-01 
  3      3  2       4    588   17 5.5354e-01 
  3      3  3       8   1029   21 2.6701e-01 
  3      3  4      16   1911   25 2.6696e-01 
  3      3  5      32   3549   35 2.6666e-01 
  3      3  6      64   6591   50 3.9731e-02 
  3      3  7     128  12675   56 3.9734e-02 
  3      3  8     256  24375   72 3.9586e-02 

```

**Comment by kronbichler** [comment]
I checked the `main` branch and got the same result, the test passes for me.

**Pull request merged**
