### PR TITLE
Add matrix-power-kernel benchmark

### PR DESCRIPTION
**Pull request by peterrum**
.. by doing local vmults during pre/post. 

The timings as they are now are not convincing. Doing 2 vmults at once is more or less as fast as doing them separately. Doing 3 vmults, is consistently slower by 10%.

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]
This is a nice benchmark. I assume the benchmark is Cartesian, as the code https://github.com/kronbichler/mf_data_locality/blob/ad0fc51ecb79bb0565fdb05889978d77bcb09183/common_code/benchmark.h#L93-L97 is missing. With that, I believe that the memory bandwidth is not that limiting. Of course, it is challenging to get the initialization done for non-affine cells (where the benefit might be bigger). Anyway, I think the present code gives also a good impression that power kernels are not as beneficial in the matrix-free context due to the higher arithmetic intensity.

**Comment by peterrum** [comment]
@kronbichler I only added Cartesian mesh, since I expected that that is the best case.

In the last commit, I have added the general case. The results are in the table:

|           | n cells | n dofs   | ratio [pk / vmult]   | power kernel with 3 vmults [s] | vmult [s] |
|-----------|---------|----------|---------|---------|--------------|
| Cartesian | 131072  | 16589601 | 3.22487 | 5.52965 | 1.71469      |
| general   | 49152   | 6246961  | 5.75258 | 11.539  | 2.00587      |

... the mapping data apparently nicely cleans out the cache (or the reshuffling of the mapping is the bottleneck). I guess mapping on the fly would not behave that bad; but I cannot image that it would be better than in the Caresian case!?

**Comment by kronbichler** [comment]
Regarding the table, what are the numbers in the table? Is higher better or lower better?

**Comment by peterrum** [comment]
I have added the units.

**Comment by kronbichler** [comment]
Great. Do we want to include a short discussion in the paper? (Clearly, this is not fully optimized, but I think it nicely illustrates that things are not straight-forward at all.)

**Comment by peterrum** [comment]
> Great. Do we want to include a short discussion in the paper? 

Yes, we can. When re-reading the paper last week, I was curious if the communication is the only bottleneck. If yes, we could have tried to interleave multiple update-ghost-value steps/compression steps and cell-integral somehow. But the serial case, which is the optimal case, does not give a lot of hope. We could reduce the number of cell batches per range to reduce the dependency region; but we are already at two batches for p=5, aren't we?

**Comment by kronbichler** [comment]
Yes indeed, I think we have 2 batches for p=5.

**Pull request merged**
